// <auto-generated />
using System;
using AircraftAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AircraftAPI.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211110073401_AddedDataAnotations")]
    partial class AddedDataAnotations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArcraftAPI.Models.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registration")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aircrafts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2021, 11, 10, 13, 4, 1, 575, DateTimeKind.Local).AddTicks(6944),
                            Location = "London Gatwick",
                            Make = "Boeing",
                            Model = "777-300ER",
                            Registration = "G-RNAC”"
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2021, 11, 10, 13, 4, 1, 576, DateTimeKind.Local).AddTicks(3912),
                            Location = "London Gatwick1",
                            Make = "Boeing1",
                            Model = "777-300ER1",
                            Registration = "G-RNAC1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
